# Generated by Django 5.2 on 2025-04-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_room_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
